# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

services:

  test:
    image: gitregistry.knut.univention.de/univention/dev/nubus-for-k8s/common-helm/testrunner:0.29.17@sha256:ba16ad762899e98226d7b5e48b4fafd85bdba96f486663499104c74013a67ec1
    profiles:
      - test
    volumes:
      - ".:/app"

  # Environment of the pre-commit linter.
  pre-commit:
    profiles:
      - test
    image: gitregistry.knut.univention.de/univention/dev/tooling/pre-commit/univention-pre-commit:latest
    volumes:
      - type: bind
        source: .
        target: /code
      - type: volume
        # pre-commit installs dependencies, having them cached speeds things up
        # a lot.
        source: pre-commit-cache
        target: /cache

volumes:
  pre-commit-cache:
